networks:
  express-network:
    driver: bridge
  nest-network:
    driver: bridge

services:
  mongo-db:
    build:
      context: ./microservices/mongo-db
      dockerfile: Dockerfile
    networks:
      - nest-network
    # ports:
    #   - 27017:27017
    volumes:
      - mongo-db-data:/data/db
    env_file:
      - ./.env
  redis:
    build:
      context: ./microservices/redis
      dockerfile: Dockerfile
    networks:
      - nest-network
    # ports:
    #   - 6379:6379
    volumes:
      - redis-data:/data
    env_file:
      - ./.env
  postgres:
    build:
      context: ./microservices/postgres
      dockerfile: Dockerfile
    networks:
      - nest-network
    # ports:
    #   - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - ./.env

  express:
    build:
      context: ./microservices/expressApp
      dockerfile: Dockerfile
    depends_on:
      - nest
    volumes:
      - npm-cache:/root/.npm
    networks:
       - express-network
    env_file:
      - ./.env
  nest:
    build:
      context: ./microservices/nest-app
      dockerfile: Dockerfile
    volumes:
      - npm-cache:/root/.npm

    depends_on:
      - redis
      - mongo-db
      - postgres
    networks:
       - nest-network
    env_file:
      - ./.env 

volumes:
  postgres-data:
  mongo-db-data:
  redis-data:
  npm-cache:
    external: false