services:
   mongo-db:
      image: mongo:latest
      container_name: mongo-db
      restart: unless-stopped
      ports:
         - '${MONGO_PORT}:${MONGO_PORT}'
      volumes:
         - mongo-db-data:/data/db
      environment:
         - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
         - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      command: ['mongod', '--port', '${MONGO_PORT}']

   redis:
      image: redis:latest
      working_dir: /data
      restart: unless-stopped
      container_name: redis
      ports:
         - '${REDIS_PORT}:${REDIS_PORT}'
      volumes:
         - redis-data:/data
      command: ['redis-server', '--requirepass', '${REDIS_PASSWORD}']

   postgres-auth:
      image: postgres:17-alpine
      container_name: postgres-auth
      restart: unless-stopped
      environment:
         - POSTGRES_PASSWORD=${AUTH_POSTGRES_PASSWORD}
         - POSTGRES_USER=${AUTH_POSTGRES_USER}
         - POSTGRES_DB=${AUTH_POSTGRES_DB}
         - POSTGRES_HOST_AUTH_METHOD=${AUTH_POSTGRES_HOST_AUTH_METHOD}
         - POSTGRES_PORT=${AUTH_POSTGRES_PORT}
      ports:
         - '${AUTH_POSTGRES_PORT}:${AUTH_POSTGRES_PORT}'
      volumes:
         - postgres-auth-data:/var/lib/postgresql/data
         - ./auth-postgres-init.sql:/docker-entrypoint-initdb.d/auth-postgres-init.sql

      command: ['postgres', '-p', '${AUTH_POSTGRES_PORT}']

   postgres-common:
      image: postgres:17-alpine
      container_name: postgres-common
      restart: unless-stopped
      environment:
         - POSTGRES_PASSWORD=${COMMON_POSTGRES_PASSWORD}
         - POSTGRES_USER=${COMMON_POSTGRES_USER}
         - POSTGRES_DB=${COMMON_POSTGRES_DB}
         - POSTGRES_HOST_AUTH_METHOD=${COMMON_POSTGRES_HOST_AUTH_METHOD}
         - POSTGRES_PORT=${COMMON_POSTGRES_PORT}
      ports:
         - '${COMMON_POSTGRES_PORT}:${COMMON_POSTGRES_PORT}'
      volumes:
         - postgres-common-data:/var/lib/postgresql/data
      command: ['postgres', '-p', '${COMMON_POSTGRES_PORT}']

volumes:
   postgres-auth-data:
   postgres-common-data:
   mongo-db-data:
   redis-data:
