name: Docker Compose Deploy

on:
   push:
      branches: ['feature/auth']
   workflow_dispatch:

jobs:
   build-and-deploy:
      runs-on: ubuntu-latest
      steps:
         - name: Checkout repository
           uses: actions/checkout@v4

         - name: Load .env.production file
           run: |
              while read -r line || [[ -n "$line" ]]; do
                if [[ $line != \#* ]] && [[ -n $line ]]; then
                  echo "$line" >> $GITHUB_ENV
                fi
              done < .env.production
           shell: bash

         - name: Set up Docker Buildx
           uses: docker/setup-buildx-action@v2

         - name: Login to Docker Hub
           uses: docker/login-action@v2
           with:
              username: ${{ secrets.DOCKER_HUB_USERNAME }}
              password: ${{ secrets.DOCKER_HUB_TOKEN }}

         - name: Build and push services
           run: |
              docker compose -f docker-compose.production.yml build
              docker compose -f docker-compose.production.yml push
