name: Docker Compose Deploy

on:
   push:
      branches: ['feature/auth']
   workflow_dispatch:

jobs:
   build-and-deploy:
      runs-on: ubuntu-latest
      steps:
         - name: Checkout repository
           uses: actions/checkout@v3

         - name: Load .env.production file
           uses: falti/load-env-file@v1
           with:
              context: root
              env-file: .env.production

         - name: Set up Docker Buildx
           uses: docker/setup-buildx-action@v2

         - name: Login to Docker Hub (if needed)
           uses: docker/login-action@v2
           with:
              username: ${{ secrets.DOCKER_HUB_USERNAME }}
              password: ${{ secrets.DOCKER_HUB_TOKEN }}

         - name: Build and push services
           run: |
              docker compose -f docker-compose.production.yml build
              docker compose -f docker-compose.production.yml push
